### ISSUE TITLE
Colors in shell?

### ISSUE THREAD

**Issue by elboletaire** [bobey/docker-gitlab-ci-runner#15]
Is there any way to enable shell colors? With the php 5.5 image I was able to see the composer result colored, but with the 5.6 image there are no colors.

As you know, coloring the output of the shell is very useful to distinguish between successful messages, error messages and warnings. I'm sure you know the difference between debugging something in notepad and doing it in a syntax highlighted editor like notepad++, atom or sublime text.

Currently the output for the php 5.6 image is completely flat, which makes it very difficult to debug when there are warnings or errors.

I'm currently creating the gitlab runner with this command:

``` bash
docker run -d \
-e CI_SERVER_URL=http://myserver.loc/ci \
-e REGISTRATION_TOKEN=myprojectregistrationtoken \
-e HOME=/root \
-e GITLAB_SERVER_FQDN=myserver.loc \
-v /var/www/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
--restart=always \
--name=metro-2015-runner \
bobey/docker-gitlab-ci-runner-php5.6
```

Is there any way to enable coloring output? Or is something with the images themselves?

**Comment by elboletaire** [comment]
Ok, found a way.. but I'm not sure if is the fastest one and it does not show some colors than your php 5.5 image shows (like the result of phpunit).

Instead of creating the runner with docker run, I've used the proper `gitlab-ci-multi-runner` like this:

``` bash
sudo gitlab-ci-multi-runner register \
--non-interactive \
--url "http://myserver.loc/ci" \
--registration-token "myprojectregistrationtoken \
--description "metro-2015-runner" \
--executor "docker" \
--docker-image bobey/docker-gitlab-ci-runner-php5.6
```

After that, I've opened the `gitlab-runner` config file located at `/etc/gitlab-runner/config.yml` and I've made some changes to it: I've added environment vars and the .ssh volume (which I don't know how to add using the `gitlab-ci-multi-runner`):

``` toml
[[runners]]
  name = "metro-2015-runner"
  url = "http://myserver/ci"
  token = "5b5bbe7830cd4773ffea0b2deab39e"
  tls-ca-file = ""
  executor = "docker"
  environment = ["CI_SERVER_URL=http://myserver.loc/ci", 
    "REGISTRATION_TOKEN=myprojectregistrationtoken", "HOME=/root", 
    "GITLAB_SERVER_FQDN=myserver.loc"
  ]
  [runners.docker]
    image = "bobey/docker-gitlab-ci-runner-php5.6"
    privileged = false
    volumes = ["/cache", "/var/www/.ssh/id_rsa:/root/.ssh/id_rsa:ro"]
```

I also required to add a line to my `.gitlab-ci.yml` file, so the container gets the correct `known_hosts`:

``` yaml
before_script:
  - ssh-keyscan -H myserver.loc > /root/.ssh/known_hosts

[...]
```

I'm sure there should be a better way... or am I wrong?
