### ISSUE TITLE
CI_SERVER_URL

### ISSUE THREAD

**Issue by jarvan4dev** [bobey/docker-gitlab-ci-runner#20]
GitlabCIMultiRunner_1  | ERROR: Registering runner... failed                 runner=nXauBpNJ status=couldn't execute POST against http://172.18.0.4:10080/ci/api/v1/runners/register.json: Post http://172.18.0.4:10080/ci/api/v1/runners/register.json: dial tcp 172.18.0.4:10080: i/o timeout
GitlabCIMultiRunner_1  | PANIC: Failed to register this runner. Perhaps you are having network problems

**Comment by jarvan4dev** [comment]
this is my docker-compose.yml

```
GitlabCIMultiRunner:
  image: sameersbn/gitlab-ci-multi-runner:latest
  volumes:
    - /Users/jarvan4dev/Documents/docker/gitlab-ci-multi-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=http://172.18.0.4:10080/ci
    - RUNNER_TOKEN=nXauBpNJRyjCs-HvePfH
    - RUNNER_DESCRIPTION=first_runner
    - RUNNER_EXECUTOR=shell
  restart: always
```

Could you show me what the CI_SERVER_URL is?
